// <auto-generated />
namespace PVT.Shop.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DropIsSheet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropIsSheet));
        
        string IMigrationMetadata.Id
        {
            get { return "201612020905452_DropIsSheet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
